export function getEnv(key: string, defaultValue?: string): string {
  const value = process.env[key]

  if (!value && !defaultValue) {
    console.warn(`⚠️  Environment variable ${key} is not set`)
  }

  return value || defaultValue || ''
}

export function getPort(): number {
  return parseInt(getEnv('PORT', '5000'), 10)
}

export function validateConfig(): void {
  const NODE_ENV = getEnv('NODE_ENV', 'development')
  const FAZER_API_KEY = getEnv('FAZER_API_KEY')

  // FAZER_API_KEY is required in production for FazerCards integration
  if (NODE_ENV === 'production') {
    if (!FAZER_API_KEY) {
      throw new Error('FAZER_API_KEY is required in production')
    }
  }

  // ADMIN_TOKEN is required in production to protect admin routes.
  // Render generates it automatically from render.yaml.
  const ADMIN_TOKEN = getEnv('ADMIN_TOKEN')
  if (!ADMIN_TOKEN && NODE_ENV === 'production') {
    throw new Error('ADMIN_TOKEN is required in production')
  }
}

export const config = {
  // Server
  PORT: getPort(),
  NODE_ENV: getEnv('NODE_ENV', 'development'),
  FRONTEND_URL: getEnv('FRONTEND_URL', 'http://localhost:3000'),

  // FazerCards (REQUIRED for production)
  FAZER_API_KEY: getEnv('FAZER_API_KEY'),
  FAZER_API_BASE_URL: getEnv('FAZER_API_BASE_URL', 'https://api.fazercards.com'),

  // MonCash REST API
  MONCASH_MODE: getEnv('MONCASH_MODE', 'sandbox'),
  MONCASH_CLIENT_ID: getEnv('MONCASH_CLIENT_ID'),
  MONCASH_CLIENT_SECRET: getEnv('MONCASH_CLIENT_SECRET'),
  MONCASH_API_BASE_URL: getEnv(
    'MONCASH_API_BASE_URL',
    'https://sandbox.moncashbutton.digicelgroup.com/Api'
  ),
  MONCASH_GATEWAY_BASE_URL: getEnv(
    'MONCASH_GATEWAY_BASE_URL',
    'https://sandbox.moncashbutton.digicelgroup.com/Moncash-middleware'
  ),
  MONCASH_RETURN_URL: getEnv(
    'MONCASH_RETURN_URL',
    'https://api.amicalpay.com/api/webhook/moncash'
  ),
  MONCASH_ALERT_URL: getEnv(
    'MONCASH_ALERT_URL',
    'https://amicalpay.com/payment-success'
  ),

  // Admin (generated by Render in production)
  ADMIN_TOKEN: getEnv('ADMIN_TOKEN'),

  // Logging
  LOG_LEVEL: getEnv('LOG_LEVEL', 'info'),
}
